# This is a sample config TOML for Valence
debug = false
extern_port = 3030
cache_url = "redis://0.0.0.0"
cache_port = "6379"
cache_password = ""
db_protocol = "mongodb://127.0.0.1"
db_url = ""
db_port = "27017"
db_user = ""
db_password = ""
body_limit = 4096
cache_ttl = 600 # cache lifetime in seconds

# Plug-in options
market = false