version: '3'

networks:
  app-tier:
    driver: bridge

services:
  cache:
    image: redis:6.2.6-alpine
    networks:
      - app-tier
    restart: always
    ports:
      - 6379:6379
    expose:
      - 6379
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data/cache
  db:
    image: bitnami/mongodb:7.0.5
    networks:
      - app-tier
    restart: always
    ports:
      - 27017:27017
    expose:
      - 27017
    # environment:
    #   MONGODB_ROOT_USER: root
    # volumes:
    #   - db:/data/db
  # valence:
  #   build: .
  #   image: valence
  #   networks:
  #     - app-tier
  #   ports:
  #     - 3030:3030
  #   expose:
  #     - 3030
  #   restart: always
  #   depends_on:
  #     - cache
  #     - db
  #   # links:
  #   #   - cache
  #   #   - db
  #   volumes:
  #     - ${PWD}/logs:/app/logs
volumes:
  cache:
    driver: local
  db:
    driver: local
