name: manual-build-and-push

permissions:
  contents: read
  packages: write
  security-events: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    uses: {{ vars.ORGANISATION_WORKFLOW_PATH }}/build.yml@main
    with:
      REGISTRY: ${{ vars.REGISTRY }}
      REPOSITORY: ${{ vars.REPOSITORY }}
      NODE_TYPE: ${{ inputs.node_type }}
